apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-iokj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ixow-tenant/rhtap-demo-app/hacbs-test-project-iokj@sha256:b26a62942d81426e378513de4fd20359b5af82010f6417481ed473fcfbf21b88
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
