apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-iokj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-iokj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-iokj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-iokj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-iokj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ixow-tenant/rhtap-demo-app/hacbs-test-project-iokj@sha256:b26a62942d81426e378513de4fd20359b5af82010f6417481ed473fcfbf21b88
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
